### PR TITLE
Make sure empty request in refract has the same properties as empty request in AST

### PR DESCRIPTION
**Pull request by pksunkara**
I have tried to change the original `BlueprintAPI.Request` class and tried to streamline it, but it kept getting more complex and got out of hand. So, I just deleted all that code and added this temporary fix for now. We can clean up some of this stuff once we remove AST.

### CODE REVIEW

**Review by kylef — COMMENTED** [review]
No test coverage or changelog entry?

**Comment by pksunkara** [comment]
This is a regression in the previous release. Will add them tomorrow.

**Comment by kylef** [comment]
> This is a regression in the previous release.

Yes, I think that's even more reason to add test coverage. This bug was already introduced one time...

**Comment by pksunkara** [comment]
Yeah, I have finished the tests. Forgot to send a PR. Will do now.

**Pull request merged**
